sudo: required
services:
- docker
jobs:
  include:
  - stage: Build & Test
    script:
    - docker-compose build
    - docker-compose run --rm api ./gradlew test
    - docker-compose run --rm ui npm run test
  - stage: Deploy
    if: (branch = develop) AND (NOT (type IN (pull_request)))
    provider: heroku
    script: "./deploy.sh"
