sudo: required
services:
- docker
jobs:
  include:
  - stage: Build & Test
    script:
    - docker-compose build
    - docker-compose run --rm api ./gradlew test
    - docker-compose run --rm ui npm run test
  - stage: Deploy
    if: (branch = master) AND (type = push)
    provider: heroku
    script: "./deploy.sh"
